version: '3'

services:
  api:
    build: .
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    command: flask run -h 0.0.0.0

  db:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
