version: '3'

services:
  api:
    build: ./app/
    ports:
      - "5000:5000"
    volumes:
      - "./app/src/:/app/src"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0

  db:
    build: ./db/
    hostname: db
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/logs:/var/logs/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}