"""empty message

Revision ID: 840a086a6df5
Revises: 
Create Date: 2021-09-07 00:52:45.231572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840a086a6df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
